import os
import re
import json
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field, field_validator
from loguru import logger

from models import Clause
from llm_client import LLMClient
from rag_engine import RAGEngine
from risk_scorer import RiskScorer
import prompts
from config import config

class LLMResponse(BaseModel):
    """Structured legal review output generated by the LLM (FR-18)."""
    original_clause_summary: str = Field(..., description="Summary of the original clause.")
    redlined_clause: str = Field(..., description="The full revised text of the clause.")
    redline_rationale: str = Field(..., description="Detailed explanation of the changes made.")
    negotiation_priority: str = Field(..., description="The priority of this change: MUST_CHANGE, SHOULD_CHANGE, or NICE_TO_HAVE.")
    walk_away_trigger: str = Field(..., description="Conditions under which we should walk away from this clause/contract.")
    confidence_score: float = Field(..., description="LLM confidence score between 0.0 and 1.0.")
    legal_disclaimer: str = Field(..., description="The mandatory legal disclaimer verbatim text.")
    fallback_mode: bool = Field(False, description="Flag indicating if fallback mode was activated.")

    @field_validator("legal_disclaimer")
    @classmethod
    def validate_disclaimer_verbatim(cls, value: str) -> str:
        if value.strip() != prompts.DISCLAIMER_TEXT.strip():
            raise ValueError(f"Disclaimer text mismatch. Expected: '{prompts.DISCLAIMER_TEXT}'")
        return value

    @field_validator("negotiation_priority")
    @classmethod
    def validate_priority(cls, value: str) -> str:
        valid_priorities = ["MUST_CHANGE", "SHOULD_CHANGE", "NICE_TO_HAVE"]
        if value not in valid_priorities:
            raise ValueError(f"Priority must be one of {valid_priorities}")
        return value

class ContractAgent:
    """Legal Agent that reviews contract clauses using a ReAct loop with tools and structured responses."""
    
    def __init__(
        self,
        llm_client: Optional[LLMClient] = None,
        rag_engine: Optional[RAGEngine] = None,
        risk_scorer: Optional[RiskScorer] = None
    ):
        self.llm_client = llm_client or LLMClient()
        self.rag_engine = rag_engine or RAGEngine()
        
        # Load risk scorer (ensuring it is initialized)
        self.risk_scorer = risk_scorer or RiskScorer(rag_engine=self.rag_engine)
        
        # Ensure RAG knowledge base is loaded
        self.rag_engine.build_or_load_vector_store()
        
        # Define native Claude tools
        self.tools = [
            {
                "name": "precedent_lookup",
                "description": "Find relevant market precedents and guidelines in the knowledge base.",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "query": {
                            "type": "string",
                            "description": "The search query (e.g., clause text, concept, or keywords)."
                        }
                    },
                    "required": ["query"]
                }
            },
            {
                "name": "jurisdiction_lookup",
                "description": "Retrieve the legal risk score for a given jurisdiction/state.",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "jurisdiction": {
                            "type": "string",
                            "description": "The name of the state or jurisdiction (e.g. California, Delaware)."
                        }
                    },
                    "required": ["jurisdiction"]
                }
            }
        ]

    def _precedent_lookup_tool(self, query: str) -> str:
        results = self.rag_engine.hybrid_search(query, rerank=True, top_n=3)
        if not results:
            return "No precedents found."
        
        formatted = []
        for idx, r in enumerate(results):
            meta = r.get("metadata", {})
            formatted.append(
                f"Precedent {idx+1}:\n"
                f"Source File: {meta.get('source_file')}\n"
                f"Title: {meta.get('title')}\n"
                f"Jurisdiction: {meta.get('jurisdiction')}\n"
                f"Category: {meta.get('clause_type')}\n"
                f"Content: {r.get('text')}\n"
            )
        return "\n---\n".join(formatted)

    def _jurisdiction_lookup_tool(self, jurisdiction: str) -> str:
        score = self.risk_scorer.lookup_jurisdiction_risk(jurisdiction)
        return f"Jurisdiction '{jurisdiction}' risk score: {score}"

    def review_clause(self, clause: Clause) -> LLMResponse:
        """Runs the ReAct loop to generate a structured redline for a clause, with RAG fallback."""
        # 1. Fetch initial RAG precedents context for the user prompt
        precedents = self.rag_engine.hybrid_search(clause.raw_text, rerank=True, top_n=3)
        precedent_context = self._format_precedent_context(precedents)
        
        # Calculate individual clause risk score
        clause_res = self.risk_scorer.score_clause(clause, precedents)
        clause_risk_score = clause_res["final_score"]
        
        # 2. Build User Prompt (FR-17)
        user_prompt = prompts.USER_PROMPT_TEMPLATE.format(
            clause_id=clause.clause_id,
            clause_type=clause.clause_type or "Unknown",
            raw_text=clause.raw_text,
            governing_law=clause.governing_law_jurisdiction or "Unknown",
            contract_value_usd=clause.contract_value_usd or 0.0,
            counterparty_name=clause.counterparty_name or "Unknown",
            risk_score=round(clause_risk_score, 4),
            one_sidedness=clause_res["one_sidedness_score"],
            market_deviation=clause_res["market_deviation_score"],
            jurisdiction_risk=clause_res["jurisdiction_risk_score"],
            value_risk=clause_res["value_risk_score"],
            precedent_context=precedent_context
        )
        
        # 3. Execute ReAct Loop (with fallback)
        try:
            final_text = self._run_react_loop(clause, user_prompt)
            response_data = self._parse_and_validate(final_text)
            return response_data
        except Exception as e:
            logger.warning(
                f"ReAct loop or response validation failed for clause {clause.clause_id}: {e}. "
                f"Triggering RAG fallback."
            )
            return self._rag_fallback(clause)

    def _format_precedent_context(self, precedents: List[dict]) -> str:
        if not precedents:
            return "No precedents found."
        formatted = []
        for idx, p in enumerate(precedents):
            meta = p.get("metadata", {})
            formatted.append(
                f"- Precedent {idx+1} from {meta.get('source_file')}: \"{p.get('text')[:300]}...\""
            )
        return "\n".join(formatted)

    def _run_react_loop(self, clause: Clause, user_prompt: str) -> str:
        """Executes the tool-calling loop with Claude."""
        messages = [
            {"role": "user", "content": user_prompt}
        ]
        
        max_turns = 3
        for turn in range(max_turns):
            logger.info(f"ReAct Loop Turn {turn+1}/{max_turns} for clause {clause.clause_id}")
            
            # Send message to Claude
            response = self.llm_client.create_message(
                system=prompts.SYSTEM_PROMPT,
                messages=messages,
                tools=self.tools
            )
            
            # Extract text blocks and tool use blocks
            text_blocks = []
            tool_calls = []
            
            for block in response.content:
                if block.type == "text":
                    text_blocks.append(block.text)
                elif block.type == "tool_use":
                    tool_calls.append(block)
            
            # Append assistant response to messages history
            messages.append({
                "role": "assistant",
                "content": response.content
            })
            
            if not tool_calls:
                # Claude has finished reasoning and returned final text
                final_text = "\n".join(text_blocks)
                return final_text
                
            # Execute tool requests
            tool_results = []
            for tool_call in tool_calls:
                tool_name = tool_call.name
                tool_id = tool_call.id
                tool_args = tool_call.input
                
                logger.info(f"Agent executing tool: {tool_name} with args: {tool_args}")
                
                try:
                    if tool_name == "precedent_lookup":
                        query = tool_args.get("query", "")
                        result = self._precedent_lookup_tool(query)
                    elif tool_name == "jurisdiction_lookup":
                        jurisdiction = tool_args.get("jurisdiction", "")
                        result = self._jurisdiction_lookup_tool(jurisdiction)
                    else:
                        result = f"Error: Unknown tool '{tool_name}'"
                except Exception as e:
                    logger.error(f"Failed to execute tool {tool_name}: {e}")
                    result = f"Error during execution: {str(e)}"
                    
                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": tool_id,
                    "content": result
                })
                
            # Append tool results as a single user message
            messages.append({
                "role": "user",
                "content": tool_results
            })
            
        raise TimeoutError("Max ReAct loop turns reached without final answer.")

    def _parse_and_validate(self, text: str) -> LLMResponse:
        """Parses LLM response JSON block and validates exact-string disclaimer match."""
        # Find JSON boundaries
        match = re.search(r'\{.*\}', text, re.DOTALL)
        if match:
            json_str = match.group(0)
        else:
            json_str = text
            
        data = json.loads(json_str)
        # LLMResponse automatically validates legal_disclaimer and negotiation_priority
        return LLMResponse(**data)

    def _rag_fallback(self, clause: Clause) -> LLMResponse:
        """Fallback mechanism if LLM fails, times out, or fails disclaimer validation (FR-21)."""
        logger.warning(f"Applying RAG Fallback suggestion for clause {clause.clause_id}")
        
        # Retrieve the best precedent passage
        precedents = self.rag_engine.hybrid_search(clause.raw_text, rerank=True, top_n=1)
        
        if precedents:
            suggested_redline = precedents[0]["text"]
            source = precedents[0]["metadata"].get("source_file", "Unknown")
            title = precedents[0]["metadata"].get("title", "Standard Playbook")
            rationale = (
                f"Fallback Mode: suggestion generated from standard precedent {source} ({title})."
            )
        else:
            suggested_redline = clause.raw_text
            rationale = "Fallback Mode: no precedents found. Suggesting original text."
            
        return LLMResponse(
            original_clause_summary="Fallback: summary unavailable.",
            redlined_clause=suggested_redline,
            redline_rationale=rationale,
            negotiation_priority="MUST_CHANGE",
            walk_away_trigger="Not specified (Fallback Mode).",
            confidence_score=0.0,
            legal_disclaimer=prompts.DISCLAIMER_TEXT,
            fallback_mode=True
        )

    def review_contract(self, filepath: str) -> List[Dict[str, Any]]:
        """Reviews a contract: parses clauses, scores risks, and runs ReAct loop for CRITICAL/HIGH ones (FR-17)."""
        logger.info(f"Reviewing contract: {filepath}")
        
        # Import parser helper
        from contract_parser import parse_contract
        
        clauses = parse_contract(filepath)
        if not clauses:
            logger.warning("No clauses parsed for contract review.")
            return []
            
        # Compute risk scores to sort clauses
        scored_clauses = []
        for clause in clauses:
            # Get precedents (needed for market deviation score)
            precedents = []
            if clause.risk_flag in ["HIGH_RISK", "REVIEW_REQUIRED"]:
                precedents = self.rag_engine.hybrid_search(clause.raw_text, rerank=True, top_n=3)
            
            scored_res = self.risk_scorer.score_clause(clause, precedents)
            score = scored_res["final_score"]
            
            # Determine clause-level risk tier
            if score >= 0.70:
                tier = "CRITICAL"
            elif score >= 0.50:
                tier = "HIGH"
            elif score >= 0.35:
                tier = "MEDIUM"
            else:
                tier = "LOW"
                
            scored_clauses.append({
                "clause": clause,
                "score": score,
                "tier": tier
            })
            
        # Filter: Only keep CRITICAL and HIGH tier clauses (FR-17)
        filtered_clauses = [
            item for item in scored_clauses if item["tier"] in ["CRITICAL", "HIGH"]
        ]
        
        # Sort by risk score descending
        sorted_clauses = sorted(filtered_clauses, key=lambda x: x["score"], reverse=True)
        
        # Capped up to max_clauses_per_run (FR-17)
        max_clauses = config.agent.max_clauses_per_run
        selected_clauses = sorted_clauses[:max_clauses]
        
        logger.info(f"Filtered {len(scored_clauses)} clauses down to {len(filtered_clauses)} CRITICAL/HIGH. Reviewing top-{len(selected_clauses)}.")
        
        redlines = []
        for item in selected_clauses:
            clause = item["clause"]
            score = item["score"]
            tier = item["tier"]
            
            logger.info(f"Reviewing {tier} clause {clause.clause_id} (Score={score:.4f})...")
            res = self.review_clause(clause)
            
            redlines.append({
                "clause_id": clause.clause_id,
                "section_number": clause.section_number,
                "raw_text": clause.raw_text,
                "clause_type": clause.clause_type,
                "risk_score": score,
                "risk_tier": tier,
                "original_clause_summary": res.original_clause_summary,
                "redlined_clause": res.redlined_clause,
                "redline_rationale": res.redline_rationale,
                "negotiation_priority": res.negotiation_priority,
                "walk_away_trigger": res.walk_away_trigger,
                "confidence_score": res.confidence_score,
                "legal_disclaimer": res.legal_disclaimer,
                "fallback_mode": res.fallback_mode
            })
            
        return redlines
