import os
import yaml
from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

def load_yaml_config(filepath: str = "config.yaml") -> Dict[str, Any]:
    if not os.path.exists(filepath):
        return {}
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
    except Exception as e:
        print(f"Error loading config.yaml: {e}")
        return {}

def load_org_profile(filepath: str = "org_profile.yaml") -> Dict[str, Any]:
    if not os.path.exists(filepath):
        return {}
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
    except Exception as e:
        print(f"Error loading org_profile.yaml: {e}")
        return {}

class LLMConfig(BaseModel):
    provider: str = "anthropic"
    model: str = "claude-sonnet-4-20250514"
    max_tokens: int = 1500
    daily_spend_limit: float = 50.00

class ParsingConfig(BaseModel):
    min_clause_chars: int = 80

class ClassifierConfig(BaseModel):
    confidence_threshold: float = 0.60
    high_risk_types: List[str] = ["Liability", "Indemnification", "IP"]

class RAGConfig(BaseModel):
    chunk_size: int = 512
    chunk_overlap: int = 64
    top_k: int = 6
    rerank_top_n: int = 3

class RiskScoringConfig(BaseModel):
    weights: Dict[str, float] = {
        "type": 0.35,
        "one_sidedness": 0.30,
        "market_deviation": 0.25,
        "jurisdiction": 0.10
    }

class AgentConfig(BaseModel):
    max_clauses_per_run: int = 10
    max_iterations: int = 3

class OutputConfig(BaseModel):
    report_dir: str = "./reports"
    log_path: str = "./agent.log"
    log_level: str = "INFO"

class SafetyConfig(BaseModel):
    legal_disclaimer: str = (
        "This output is generated by an AI agent and does not constitute legal advice. "
        "All suggested redlines must be reviewed and approved by qualified legal counsel before use."
    )

class AppConfig(BaseModel):
    llm: LLMConfig = LLMConfig()
    parsing: ParsingConfig = ParsingConfig()
    classifier: ClassifierConfig = ClassifierConfig()
    rag: RAGConfig = RAGConfig()
    risk_scoring: RiskScoringConfig = RiskScoringConfig()
    agent: AgentConfig = AgentConfig()
    output: OutputConfig = OutputConfig()
    safety: SafetyConfig = SafetyConfig()
    org_profile: Dict[str, Any] = {}

# Load YAML datasets
yaml_data = load_yaml_config()
org_data = load_org_profile()

# Extract segments
llm_dict = yaml_data.get("llm", {})
parsing_dict = yaml_data.get("parsing", {})
classifier_dict = yaml_data.get("classifier", {})
rag_dict = yaml_data.get("rag", {})
risk_scoring_dict = yaml_data.get("risk_scoring", {})
agent_dict = yaml_data.get("agent", {})
output_dict = yaml_data.get("output", {})
safety_dict = yaml_data.get("safety", {})

config = AppConfig(
    llm=LLMConfig(**llm_dict) if llm_dict else LLMConfig(),
    parsing=ParsingConfig(**parsing_dict) if parsing_dict else ParsingConfig(),
    classifier=ClassifierConfig(**classifier_dict) if classifier_dict else ClassifierConfig(),
    rag=RAGConfig(**rag_dict) if rag_dict else RAGConfig(),
    risk_scoring=RiskScoringConfig(**risk_scoring_dict) if risk_scoring_dict else RiskScoringConfig(),
    agent=AgentConfig(**agent_dict) if agent_dict else AgentConfig(),
    output=OutputConfig(**output_dict) if output_dict else OutputConfig(),
    safety=SafetyConfig(**safety_dict) if safety_dict else SafetyConfig(),
    org_profile=org_data.get("org_profile", {})
)
