from typing import List, Optional
from pydantic import BaseModel, Field

class Clause(BaseModel):
    """Represents a raw legal clause extracted from a contract document."""
    clause_id: Optional[str] = Field(
        None, 
        description="Unique identifier for the clause, e.g. CLS_001."
    )
    section_number: Optional[str] = Field(
        None,
        description="The section number or header of the clause, e.g., '1. Purpose' or 'Section 3.1'."
    )
    raw_text: str = Field(
        ..., 
        description="The raw textual content of the clause."
    )
    page_number: Optional[int] = Field(
        None, 
        description="The page number where the clause was located in the source document."
    )
    
    # Enriched metadata fields
    counterparty_name: Optional[str] = Field(
        None,
        description="The name of the counterparty (fictional in samples)."
    )
    contract_type: Optional[str] = Field(
        None,
        description="The type of the contract, e.g., NDA, MSA, SaaS."
    )
    governing_law_jurisdiction: Optional[str] = Field(
        None,
        description="The jurisdiction of governing law."
    )
    effective_date: Optional[str] = Field(
        None,
        description="The contract effective date (ISO 8601 format)."
    )
    contract_value_usd: Optional[float] = Field(
        None,
        description="The total contract value in USD."
    )

class ClassifiedClause(BaseModel):
    """Represents a clause that has been classified into a specific legal category."""
    clause: Clause = Field(
        ..., 
        description="The raw clause that was classified."
    )
    category: str = Field(
        ..., 
        description="The classified category of the clause (e.g., Confidentiality, Governing Law, Indemnification)."
    )
    confidence: float = Field(
        ..., 
        description="The classification confidence score, typically between 0.0 and 1.0.", 
        ge=0.0, 
        le=1.0
    )

class RiskScore(BaseModel):
    """Represents the assessed risk rating of a clause or contract document."""
    score: int = Field(
        ..., 
        description="Numerical risk rating, e.g. from 1 (Low) to 5 (Critical).", 
        ge=1, 
        le=5
    )
    label: str = Field(
        ..., 
        description="Qualitative risk label corresponding to the score (e.g., Low, Medium, High, Critical)."
    )
    explanation: str = Field(
        ..., 
        description="Detailed explanation and reasoning for the risk rating."
    )
    remedy: Optional[str] = Field(
        None, 
        description="Suggested text or action to mitigate the identified risk."
    )

class LLMResponse(BaseModel):
    """Structured legal review output generated by the LLM."""
    contract_id: Optional[str] = Field(
        None, 
        description="The unique identifier of the contract analyzed, e.g. CTR_001."
    )
    classified_clauses: List[ClassifiedClause] = Field(
        default_factory=list, 
        description="List of classified clauses identified in the contract."
    )
    overall_risk_score: RiskScore = Field(
        ..., 
        description="The aggregated risk assessment for the entire contract."
    )
    summary: str = Field(
        ..., 
        description="A high-level legal summary of the contract's contents."
    )
    key_obligations: List[str] = Field(
        default_factory=list, 
        description="List of key obligations or deadlines identified in the contract."
    )
    recommendations: List[str] = Field(
        default_factory=list, 
        description="Actionable recommendations for the contract negotiation."
    )
