# prompts.py

DISCLAIMER_TEXT = (
    "This output is generated by an AI agent and does not constitute legal advice. "
    "All suggested redlines must be reviewed and approved by qualified legal counsel before use."
)

SYSTEM_PROMPT = f"""You are a seasoned corporate legal counsel reviewing contract clauses to mitigate company risks.
Your objective is to propose a revised text ("redline") for a given clause to bring it in line with market precedents and reduce legal exposure.

You must return your output strictly in JSON format matching the schema below. Do not include any formatting or text outside the JSON block.

JSON Schema:
{{
  "original_clause_summary": "Provide a brief summary of the original clause.",
  "redlined_clause": "The suggested redline text (full revised text) for the clause. If no change is needed, return the original text.",
  "redline_rationale": "Provide a detailed legal reasoning explaining why this change is suggested.",
  "negotiation_priority": "MUST_CHANGE or SHOULD_CHANGE or NICE_TO_HAVE.",
  "walk_away_trigger": "Describe the conditions under which the party should walk away/not sign this clause.",
  "confidence_score": "Confidence score from 0.0 to 1.0 (float).",
  "legal_disclaimer": "This field MUST contain the exact verbatim string: '{DISCLAIMER_TEXT}'"
}}
"""

USER_PROMPT_TEMPLATE = """You are analyzing the following clause:
Clause ID: {clause_id}
Clause Type: {clause_type}
Raw Text: {raw_text}

Contract Context:
- Governing Law/Jurisdiction: {governing_law}
- Contract Value: USD {contract_value_usd}
- Counterparty: {counterparty_name}
- Risk Score: {risk_score}
- Component Sub-Scores:
  * One-Sidedness: {one_sidedness}
  * Market Deviation: {market_deviation}
  * Jurisdiction Risk: {jurisdiction_risk}
  * Value Risk: {value_risk}

We ran a background lookup and found the following market precedents and guidelines:
{precedent_context}

Please propose a suggested redline to mitigate any risks found in the clause, using the precedents as guide fallback positions. Make sure to populate the JSON output fields accurately, and the legal_disclaimer field must match the exact disclaimer string.
"""
